### ISSUE TITLE
QVCA wrong Parts in List

### ISSUE THREAD

**Issue by tmmmmm** [jakplugg/Neutron_Sound_build_docs#1]
The U1-6 seem to be mislabelled in the Parts-Sheet. It says:
4x TL074 (U1, U2, U3, U4)
1x TL072 (U5)
(U6 is missing)
The mouser cart seems to be correct, as it includes 4 TL072 (U2, U3, U4, U6) and 2 TL074 (U1, U5) - the part numbers are elaborated guesses ;)

**Comment by pferreir** [comment]
Agreed. Those part numbers can't be correct.

**Comment by jakplugg** [comment]
Where are you getting that parts list from? https://docs.google.com/spreadsheets/d/1yWP0SEDUn4MFoWlR4tSw32LnQw3czUZVgWfFrcoWUo0/edit#gid=1411372261 shows the right amount of TL072 and TL074

**Comment by pferreir** [comment]
[This link](https://docs.google.com/document/d/18ugqw1H-yLdrjC2lz874nJ2580L4D3nNiDvHTrcNREM/edit). It's the one inside `Neutron Sound QVCA Build Guide.doc.gdoc`.
BTW it would be great to add a README with direct links to the docs.

**Comment by jakplugg** [comment]
Ah, ok, I did not actually write that doc, i'll see what i can do about editing or getting it fixed. thanks!

**Comment by pferreir** [comment]
I didn't find the "right" parts list anywhere. And you're linking this document from this repo anyway.

By the way, it was an easy build and it works like a charm, thanks!
